apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-service
    namespace: ec-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user-service
    template:
        metadata:
            labels:
                app: user-service
        spec:
            containers:
                - name: user-service
                  image: user-service:0.0.1-SNAPSHOT
                  ports:
                    - containerPort: 8100
                  env:
                    - name: DB_HOST
                      value: "postgres"
                    - name: DB_PORT
                      value: "5432"
                    - name: DB_NAME
                      value: "mydatabase"
                    - name: DB_USER
                      value: "postgres"
                    - name: DB_PASSWORD
                      value: "Zaq12wsx"
