apiVersion: v1
kind: Service
metadata:
    name: user-service
    namespace: ec-app
spec:
    type: LoadBalancer
    ports:
        - port: 8100
          targetPort: 8100
    selector:
        app: user-service
